<?php

declare(strict_types=1);

namespace App\Models;

use App\Models\Concerns\Auditable;
use App\Services\Academic\StudentAccessService;
use App\Support\Audit\AuditAction;
use Database\Factories\EnrollmentFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Support\Facades\DB;

/**
 * Tenant-owned. Student <-> Class <-> Course Package: which package a
 * student enrolled in for a given class session, billed via the package's
 * fee tier (see EnrollmentService::enrollInPackage()). Modelled as a full
 * Eloquent model (its own `id`, queryable on its own) rather than a
 * `belongsToMany` pivot, so it can carry that metadata and be looked up
 * directly without always going through one side's relation.
 *
 * `enrollments_code` is a human-readable per-student sequence code
 * (`{student_code}-{NN}`, e.g. `NTS-000008-01`), generated by
 * EnrollmentService::generateEnrollmentCode() — no FormRequest ever exposes
 * it as an input field, so it stays fillable without being client-settable.
 *
 * @property int $student_id
 * @property int $class_id
 * @property int|null $table_id Which physical table in the class's classroom this student sits at -- see ClassroomTable.
 * @property int|null $course_package_id
 * @property int|null $academic_program_id
 * @property string $status
 * @property string|null $enrollments_code
 */
#[Fillable([
    'student_id', 'class_id', 'table_id', 'course_package_id', 'academic_program_id',
    'enrolled_at', 'status', 'enrollments_code',
])]
class Enrollment extends Model
{
    use Auditable, HasFactory;

    protected $connection = 'tenant';

    /** @use HasFactory<EnrollmentFactory> */
    public const STATUS_NOT_STARTED = 'not_started';

    public const STATUS_ACTIVE = 'active';

    public const STATUS_EXAM_READY = 'exam_ready';

    public const STATUS_COMPLETED = 'completed';

    public const STATUS_ABANDONED = 'abandoned';

    public const STATUS_STOPPED = 'stopped';

    public const STATUS_SUSPENDED = 'suspended';

    /**
     * Not a status an admin ever picks from the status-management menu —
     * purely internal bookkeeping for a row closed by
     * EnrollmentService::cancel() (or, historically, a row superseded by a
     * transfer — transfers now update in place). See STATUSES_MANAGEABLE
     * for the set that actually appears in that menu.
     */
    public const STATUS_DROPPED = 'dropped';

    /**
     * The statuses selectable from the "manage status" menu — everything
     * except STATUS_DROPPED, which only ever happens as a side effect of
     * cancelling, never a direct choice.
     */
    public const STATUSES_MANAGEABLE = [
        self::STATUS_NOT_STARTED, self::STATUS_ACTIVE, self::STATUS_EXAM_READY, self::STATUS_COMPLETED,
        self::STATUS_ABANDONED, self::STATUS_STOPPED, self::STATUS_SUSPENDED,
    ];

    /**
     * Only a Studying student keeps their table. Once they're stopped,
     * suspended, completed etc. the seat is free for someone else — the
     * available-tables picker, every "table already taken" check, and the
     * enrollments_class_table_active_unique DB index all use this one rule.
     * A student returning to Studying whose old table was re-assigned in the
     * meantime gets it cleared (see EnrollmentService::changeStatus()).
     */
    public const TABLE_HOLDING_STATUS = self::STATUS_ACTIVE;

    /** Which of STATUSES_MANAGEABLE require a reason + effective date — see EnrollmentService::changeStatus(). */
    public const STATUSES_REQUIRING_REASON = [self::STATUS_ABANDONED, self::STATUS_STOPPED, self::STATUS_SUSPENDED];

    /**
     * Set by EnrollmentService::cancel()/transferClass() immediately before
     * saving, purely to let auditActionForDirty()/auditDescriptionForChange()
     * below log "cancelled"/"transferred" instead of a plain STATUS_CHANGE/
     * UPDATE column-diff. Real PHP properties, not Eloquent attributes —
     * never persisted, never touch the `enrollments` table.
     */
    public ?string $auditReason = null;

    public ?string $auditTransferToClass = null;

    /** PHP-level mirror of the column's DB default — see Building for why. */
    protected $attributes = [
        'status' => self::STATUS_ACTIVE,
    ];

    protected function casts(): array
    {
        return [
            'enrolled_at' => 'date',
        ];
    }

    /**
     * Keeps the student's login in step with whether they're still studying
     * — see StudentAccessService. On the model, not in EnrollmentService,
     * because status changes come from several paths (create, the status
     * menu, cancel/transfer, imports). Deferred to commit so a rolled-back
     * change never touches the (central) user row.
     */
    protected static function booted(): void
    {
        $sync = function (self $enrollment): void {
            DB::connection('tenant')->afterCommit(function () use ($enrollment) {
                $student = $enrollment->student()->first();

                if ($student !== null) {
                    app(StudentAccessService::class)->sync($student);
                }
            });
        };

        static::saved(function (self $enrollment) use ($sync) {
            if ($enrollment->wasRecentlyCreated || $enrollment->wasChanged('status')) {
                $sync($enrollment);
            }
        });
        static::deleted($sync);
    }

    public function student(): BelongsTo
    {
        return $this->belongsTo(Student::class);
    }

    public function schoolClass(): BelongsTo
    {
        return $this->belongsTo(SchoolClass::class, 'class_id');
    }

    public function table(): BelongsTo
    {
        return $this->belongsTo(ClassroomTable::class, 'table_id');
    }

    public function coursePackage(): BelongsTo
    {
        return $this->belongsTo(CoursePackage::class);
    }

    public function academicProgram(): BelongsTo
    {
        return $this->belongsTo(AcademicProgram::class);
    }

    public function attendanceRecords(): HasMany
    {
        return $this->hasMany(AttendanceRecord::class);
    }

    public function statusHistories(): HasMany
    {
        return $this->hasMany(EnrollmentStatusHistory::class);
    }

    public function transferHistories(): HasMany
    {
        return $this->hasMany(EnrollmentTransferHistory::class);
    }

    /** The InvoiceItem(s) billed for this enrollment — see InvoiceItem::reference(). */
    public function invoiceItems(): MorphMany
    {
        return $this->morphMany(InvoiceItem::class, 'reference');
    }

    /**
     * Whether any money has actually been received against this enrollment —
     * the gate EnrollmentService::transferClass() uses to decide whether the
     * student's COURSE (not just class/room) may still be changed. Computed
     * from the loaded relation when available (EnrollmentController eager
     * loads `invoiceItems.invoice` for exactly this reason) so listing a
     * page of enrollments doesn't fire one extra query per row.
     *
     * Also counts money received on this student's DROPPED enrollments for
     * the same course package. The old transferClass() dropped the original
     * enrollment and created a new one instead of updating in place, so the
     * payment for those students still sits on the dropped row, and only
     * looking at this row's own invoices let a paid (or partly paid) student's
     * course be changed.
     */
    public function isPaid(): bool
    {
        $paidOwn = $this->relationLoaded('invoiceItems')
            ? $this->invoiceItems->contains(fn (InvoiceItem $item) => (float) $item->invoice?->paid_amount > 0)
            : $this->invoiceItems()->whereHas('invoice', fn (Builder $query) => $query->where('paid_amount', '>', 0))->exists();

        if ($paidOwn || $this->course_package_id === null) {
            return $paidOwn;
        }

        return InvoiceItem::query()
            ->where('reference_type', $this->getMorphClass())
            ->whereIn('reference_id', static::query()
                ->select('id')
                ->where('student_id', $this->student_id)
                ->where('course_package_id', $this->course_package_id)
                ->where('status', self::STATUS_DROPPED)
                ->whereKeyNot($this->getKey()))
            ->whereHas('invoice', fn (Builder $query) => $query->where('paid_amount', '>', 0))
            ->exists();
    }

    /**
     * @param  Builder<static>  $query
     */
    public function scopeActive(Builder $query): void
    {
        $query->where('status', self::STATUS_ACTIVE);
    }

    /**
     * No APPROVE/REJECT here: this system has no pending-approval workflow
     * for an enrollment today (see $this::STATUS_*) — only CREATE, UPDATE,
     * DELETE, and STATUS_CHANGE actually happen. Add them if/when an
     * approval step is introduced.
     */
    public function auditModule(): string
    {
        return 'Enrollments';
    }

    /**
     * @param  array<string, mixed>  $dirty
     */
    protected function auditActionForDirty(array $dirty): string
    {
        if ($this->auditTransferToClass !== null) {
            return AuditAction::ENROLLMENT_TRANSFERRED;
        }

        if (array_key_exists('status', $dirty) && $dirty['status'] === self::STATUS_DROPPED) {
            return AuditAction::ENROLLMENT_CANCELLED;
        }

        return array_key_exists('status', $dirty) ? AuditAction::STATUS_CHANGE : AuditAction::UPDATE;
    }

    /**
     * @param  array<string, mixed>  $old
     * @param  array<string, mixed>  $new
     */
    protected function auditDescriptionForChange(string $action, array $old, array $new): ?string
    {
        if ($action === AuditAction::ENROLLMENT_CANCELLED) {
            return "Cancelled enrollment {$this->auditDisplayName()}".($this->auditReason ? ": {$this->auditReason}" : '');
        }

        if ($action === AuditAction::ENROLLMENT_TRANSFERRED) {
            return "Transferred enrollment {$this->auditDisplayName()} to class {$this->auditTransferToClass}";
        }

        if ($action === AuditAction::STATUS_CHANGE) {
            $description = "Changed enrollment {$this->auditDisplayName()} status from {$old['status']} to {$new['status']}";

            return $this->auditReason ? "{$description}: {$this->auditReason}" : $description;
        }

        return null;
    }
}
