<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'

import ExamApplicationFormModal from '@/components/admin/ExamApplicationFormModal.vue'
import ExaminationTabs from '@/components/admin/ExaminationTabs.vue'
import BaseAlert from '@/components/ui/BaseAlert.vue'
import BaseButton from '@/components/ui/BaseButton.vue'
import BasePagination from '@/components/ui/BasePagination.vue'
import DataTable from '@/components/ui/DataTable.vue'
import { usePaginatedResource } from '@/composables/usePaginatedResource'
import { examApplicationsService, type ExamApplication } from '@/services/examApplications'
import { useAuthStore } from '@/stores/auth'
import { ApiRequestError } from '@/types/api'
import { formatDate } from '@/utils/date'

/**
 * Every STATUS_MAKE_UP application — generated by ExamScoreService::record()
 * when the Grades tab's "Make-up Exam" checkbox is saved. Already scoreable
 * (see ExamApplication::scopeScoreable()), no approve/reject step here —
 * this tab exists purely to schedule a retake's exam date/room/table (via
 * the same Application Form every other exam edit uses) and to keep make-up
 * rows out of the main Exams tab's noise.
 */
const { t } = useI18n()
const auth = useAuthStore()

const canEdit = computed(() => auth.can('exam-applications.update'))
const canDelete = computed(() => auth.can('exam-applications.delete'))

const { items, meta, loading, error, setPage, fetch } = usePaginatedResource<ExamApplication>((query) =>
  examApplicationsService.list({ ...query, filter: { ...query.filter, status: 'make_up' } }),
)

onMounted(() => void fetch())

const columns = [
  { key: 'student_code', label: t('admin.exams.columnStudentCode') },
  { key: 'full_name', label: t('admin.exams.columnFullName') },
  { key: 'book', label: t('admin.exams.columnBook') },
  { key: 'exam_date', label: t('admin.exams.columnExamDate') },
  { key: 'time_exam', label: t('admin.exams.columnTimeExam') },
  { key: 'table_no', label: t('admin.exams.columnTableNumber') },
  { key: 'created_at', label: t('admin.makeUpExam.columnCreatedAt') },
  { key: 'actions', label: t('admin.exams.columnActions') },
]

function fmtDate(value: string | null): string {
  return formatDate(value)
}

function timeRange(a: ExamApplication): string {
  const timeIn = a.exam_time?.slice(0, 5)
  const timeOut = a.exam_time_out?.slice(0, 5)
  if (!timeIn && !timeOut) return '—'
  return `${timeIn ?? '—'} - ${timeOut ?? '—'}`
}

const acting = ref<number | null>(null)
const actionError = ref<string | null>(null)

async function remove(application: ExamApplication) {
  if (!confirm(t('admin.makeUpExam.confirmDelete'))) return

  acting.value = application.id
  actionError.value = null
  try {
    await examApplicationsService.remove(application.id)
    await fetch()
  } catch (err) {
    actionError.value = err instanceof ApiRequestError ? err.message : t('admin.exams.actionFailed')
  } finally {
    acting.value = null
  }
}

const formModalOpen = ref(false)
const editingEnrollmentCode = ref<string | null>(null)

function openEdit(application: ExamApplication) {
  editingEnrollmentCode.value = application.enrollment_code
  formModalOpen.value = true
}
</script>

<template>
  <div>
    <ExaminationTabs />

    <div class="mb-6">
      <h1 class="text-xl font-semibold text-neutral-900">{{ t('admin.makeUpExam.title') }}</h1>
      <p class="mt-1 text-sm text-neutral-500">{{ t('admin.makeUpExam.subtitle') }}</p>
    </div>

    <BaseAlert v-if="error" variant="danger" class="mb-4">{{ error }}</BaseAlert>
    <BaseAlert v-if="actionError" variant="danger" class="mb-4">{{ actionError }}</BaseAlert>

    <DataTable :columns="columns" :rows="items" row-key="id" :loading="loading" :empty-message="t('admin.makeUpExam.emptyMessage')">
      <template #cell-student_code="{ row }">{{ (row as ExamApplication).student.student_code }}</template>
      <template #cell-full_name="{ row }">{{ (row as ExamApplication).student.name }}</template>
      <template #cell-book="{ row }">{{ (row as ExamApplication).book?.title ?? (row as ExamApplication).enrollment.course_package?.name ?? '—' }}</template>
      <template #cell-exam_date="{ row }">{{ fmtDate((row as ExamApplication).exam_date) }}</template>
      <template #cell-time_exam="{ row }">{{ timeRange(row as ExamApplication) }}</template>
      <template #cell-table_no="{ row }">{{ (row as ExamApplication).table?.name ?? (row as ExamApplication).table_no ?? '—' }}</template>
      <template #cell-created_at="{ row }">{{ fmtDate((row as ExamApplication).created_at) }}</template>
      <template #cell-actions="{ row }">
        <div class="flex gap-2">
          <BaseButton
            v-if="canEdit"
            size="sm"
            variant="outline"
            :disabled="acting === (row as ExamApplication).id"
            @click="openEdit(row as ExamApplication)"
          >
            {{ t('common.edit') }}
          </BaseButton>
          <BaseButton
            v-if="canDelete"
            size="sm"
            variant="danger"
            :disabled="acting === (row as ExamApplication).id"
            @click="remove(row as ExamApplication)"
          >
            {{ t('common.remove') }}
          </BaseButton>
        </div>
      </template>
    </DataTable>

    <BasePagination v-if="meta" :meta="meta" sticky class="mt-4" @update:page="setPage" />

    <ExamApplicationFormModal v-model="formModalOpen" :initial-enrollment-code="editingEnrollmentCode" @saved="fetch" />
  </div>
</template>
