<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Removes the legacy book-based enrollment path (`book_id`, `fee`, `fee_type`)
 * and the status-reason denormalization (`status_reason`,
 * `status_effective_date` — already fully covered by
 * `enrollment_status_histories`, see that table). `study_mode_id` is dropped
 * too: it was never set to a non-null value by any code path. Course-package
 * enrollment already carries fee/book information, so none of this is
 * replaced — it's simply no longer needed.
 *
 * Adds `enrollments_code`, a human-readable per-student sequence code
 * (`{student_code}-{NN}`, e.g. `NTS-000008-01`) generated by
 * EnrollmentService — nullable so factory-created test rows don't need one.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::statement('ALTER TABLE enrollments DROP CONSTRAINT IF EXISTS enrollments_book_xor_package');
        DB::statement('DROP INDEX IF EXISTS enrollments_student_class_book_active_unique');

        Schema::table('enrollments', function (Blueprint $table) {
            $table->dropColumn(['book_id', 'fee', 'study_mode_id', 'fee_type', 'status_reason', 'status_effective_date']);

            $table->string('enrollments_code')->nullable()->unique()->after('id');
        });
    }

    public function down(): void
    {
        Schema::table('enrollments', function (Blueprint $table) {
            $table->dropUnique(['enrollments_code']);
            $table->dropColumn('enrollments_code');

            $table->unsignedBigInteger('book_id')->nullable()->after('class_id');
            $table->decimal('fee', 10, 2)->nullable()->after('enrolled_at');
            $table->unsignedBigInteger('study_mode_id')->nullable()->after('academic_program_id');
            $table->string('fee_type', 20)->nullable()->after('fee');
            $table->text('status_reason')->nullable()->after('status');
            $table->date('status_effective_date')->nullable()->after('status_reason');
        });

        DB::statement("CREATE UNIQUE INDEX enrollments_student_class_book_active_unique ON enrollments (student_id, class_id, book_id) WHERE status <> 'dropped'");
        DB::statement('ALTER TABLE enrollments ADD CONSTRAINT enrollments_book_xor_package CHECK ((book_id IS NOT NULL)::int + (course_package_id IS NOT NULL)::int = 1)');
    }
};
